package ru.stqa.pft.addressbook.tests;// Generated by Selenium IDE

import org.testng.annotations.Test;
import ru.stqa.pft.addressbook.model.NameData;

public class ContactDeletionTest extends TestBase{

  @Test
  public void testGroupDeletion() {
    app.getNavigationHelper().gotoHomePage();
    if (! app.getContactHelper().isContactThere()) {
      app.getContactHelper().createContactShort(new NameData("ewdfe", null, null, null));
        }
    app.getContactHelper().selectContact();
    app.getContactHelper().deleteSelectedContacts();
    app.getNavigationHelper().gotoHomePage();
  }

}
